### ISSUE TITLE
Release latest version to chrome app store

### ISSUE THREAD

**Issue by stephenway** [livestyle/re-view#1]
Seems as though 2.1.2 is the released version, do you know when 2.1.3 will be released?
https://chrome.google.com/webstore/detail/emmet-review/epejoicbhllgiimigokgjdoijnpaphdp?hl=en-US

Thanks

**Comment by sergeche** [comment]
Actually, this is the base standalone web app for main Re:view for testing in browser. The Chrome plugin has [its own repo](https://github.com/emmetio/re-view-chrome) and includes this base app as dependency. Chrome plugin has different version number, 2.1.2, which already includes v2.1.3 of base app.

PS: yes, I know I have to do a better repo maintenance but don’t have much time for this now :)
